security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:backend_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/backenddb
#    username: postgres
#    password: root1234
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create

